const chainData = [
  {
    chainId: 10,
    name: "Optimism",
    isL1: false,
    sendingEnabled: true,
    icon: "https://media.socket.tech/networks/optimism.svg",
    receivingEnabled: true,
    refuel: {
      sendingEnabled: true,
      receivingEnabled: true,
    },
    rpcs: ["https://mainnet.optimism.io/"],
    currency: {
      address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
      icon: "https://maticnetwork.github.io/polygon-token-assets/assets/eth.svg",
      minNativeCurrencyForGas: "900000000000000",
    },
    explorers: ["https://optimistic.etherscan.io"],
  },
  {
    chainId: 137,
    name: "Polygon",
    icon: "https://media.socket.tech/networks/polygon.svg",
    isL1: false,
    sendingEnabled: true,
    receivingEnabled: true,
    refuel: {
      sendingEnabled: true,
      receivingEnabled: true,
    },
    currency: {
      address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      icon: "https://maticnetwork.github.io/polygon-token-assets/assets/matic.svg",
      name: "Matic",
      symbol: "MATIC",
      decimals: 18,
      minNativeCurrencyForGas: "30000000000000000",
    },
    rpcs: [
      "https://rpc-mainnet.matic.network",
      "wss://ws-mainnet.matic.network",
      "https://rpc-mainnet.matic.quiknode.pro",
      "https://matic-mainnet.chainstacklabs.com",
    ],
    explorers: ["https://polygonscan.com"],
  },
  {
    chainId: 8453,
    name: "Base",
    isL1: false,
    sendingEnabled: true,
    refuel: {
      sendingEnabled: true,
      receivingEnabled: true,
    },
    icon: "https://media.socket.tech/networks/base.svg",
    receivingEnabled: true,
    rpcs: ["https://mainnet.base.org/"],
    currency: {
      address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
      icon: "https://maticnetwork.github.io/polygon-token-assets/assets/eth.svg",
      minNativeCurrencyForGas: "900000000000000",
    },
    explorers: ["https://basescan.org"],
  },
  {
    chainId: 34443,
    name: "Mode",
    isL1: false,
    sendingEnabled: true,
    refuel: {
      sendingEnabled: false,
      receivingEnabled: false,
    },
    icon: "https://media.socket.tech/networks/mode.svg",
    receivingEnabled: true,
    rpcs: ["https://mainnet.mode.network"],
    currency: {
      address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
      icon: "https://maticnetwork.github.io/polygon-token-assets/assets/eth.svg",
      minNativeCurrencyForGas: "900000000000000",
    },
    explorers: ["https://modescan.io"],
  },
];

export default chainData;
